services:
  db:
    image: postgres:16-alpine
    container_name: horacerta_db
    environment:
      POSTGRES_USER: horacerta
      POSTGRES_PASSWORD: horacerta123
      POSTGRES_DB: horacerta
    ports:
      - "5433:5432"
    volumes:
      - horacerta_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U horacerta"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: horacerta_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  horacerta_data:
